[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mystic_client"
path = "lib.rs"

[dependencies]
mio = {version = "0.8.6", features = ["net", "os-poll"]}
pyo3 = { version = "0.18.2", features = ["extension-module"] }
protocol = {path="../protocol"}
